# sudo: false

language: python

python:
  - 2.7
  - 3.6

before_install:
  - sudo apt-get install libproj-dev
  - pip install coveralls
  - pip install pytest-cov
  - pip install pytest-mpl
  - pip install cython

install:
  - pip install -r requirements.txt

script:
  - python run_tests.py

after_success:
   - coveralls
